#b)
print("Hei, la oss prøve et flott valutaspill")
print()
print("1. Hvilken valuta er dette? " + u'\u20A4')
print("A. Euro, B. Pund, C. Lira")
svar = input("Ditt svar: ")
if(svar == "C" or svar == "c"): print("Korrekt svar!")
else: print ("Feil svar! Riktig svar var C")
print()
print("2. Hvilken valuta er dette? " + u'\u20A4')
print("A. NOK, B. Dollar, C. Peso")
svar = input("Ditt svar: ")
if(svar == "B" or svar == "b"): print("Korrekt svar!")
else: print("Feil svar! Riktig svar var B")
print()
print("3. Hvilken valuta er dette? " + u'\u20BF')
print("A. Cent, B. Baht, C. Bitcoin")
svar = input("Ditt svar: ")
if(svar == "C" or svar == "c"): print("Korrekt svar!")
else: print("Feil svar! Riktig svar var C")


